### ISSUE TITLE
Error running hugo after adding Niello

### ISSUE THREAD

**Issue by f17nn** [guangmean/Niello#1]
Hi, 

I tried to add you theme to my existing hugo setup and I'm getting this error
Error: Error building site: failed to render pages: render of "home" failed:  execute of template failed: template: index.html:26:44: executing "index.html" at <dateFormat "Monday, ...>: error calling dateFormat: unable to cast <nil> of type <nil> to Time

Do you know what it could be?

**Comment by guangmean** [comment]
Hi @f17nn
Which version of hugo you are launched ?  Would you please give me a showcase of the Frontmater in your Markdown(.md) file?

Thanks

**Comment by guangmean** [comment]
Replace the .dateFormat function with .PublishDate.Format fixed this issue.

**Comment by f17nn** [comment]
Sorry, but replace it where?

**Comment by guangmean** [comment]
Please see my latest push of layouts/index.html and layouts/post/single.html on github.com

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: f17nn <notifications@github.com>
发送时间: 星期三, 一月 23, 2019 15:28
收件人: guangmean/Niello
抄送: guangmean; State change
主题: Re: [guangmean/Niello] Error running hugo after adding Niello (#1)


Sorry, but replace it where?

―
