### ISSUE TITLE
Does Niello support adding additional tags?

### ISSUE THREAD

**Issue by tzkyard** [guangmean/Niello#2]
Thank you for designing such a beautiful Hugo theme ！But I still have a problem: Does Niello support adding additional tags?  like this:
![image](https://user-images.githubusercontent.com/49138808/55602987-f21bd080-579a-11e9-9fd5-5a1df4b37034.png)

**Comment by guangmean** [comment]
Hi @tzkyard Niello is not support add custom tags currently like what you described. We'll consider add the feature in the next version.

But you can add other tags manually by edit themes/Niello/layouts/index.html on line 19

**Comment by tzkyard** [comment]
OK, Thank you for your reply. Looking forward to the next version of Niello.

**Comment by guangmean** [comment]
Dear @tzkyard , Niello 1.0 which support custom navigations was released, you can add custom tags  with edit the site config.toml like bellow:

[menu]
    [[menu.niello]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.niello]]
    name = "Contact"
    url = "/post/contact/"
    weight = 2

![Screen Shot 2019-04-08 at 18 08 01](https://user-images.githubusercontent.com/545564/55716429-8ac78000-5a29-11e9-93bc-163f725def35.png)

**Comment by tzkyard** [comment]
Wow, that's so great！
(Can I speak chinese?  hahaha...)是否可以在每篇文章的正文底部增加`上一篇文章XXX` `下一篇文章XXX`之类的导航栏呢？类似这样的：  
![image](https://user-images.githubusercontent.com/49138808/55735140-5d8fc780-5a53-11e9-875f-44efade37ceb.png)
另外就是代码高亮师父可以做到对比度大一些呢，如下图对比度似乎不太明显：
![image](https://user-images.githubusercontent.com/49138808/55735376-c70fd600-5a53-11e9-84c2-d5a18871dbd1.png)

**Comment by guangmean** [comment]
Thanks for your feedback. We'll optimize this issue later.

**Comment by guangmean** [comment]
Done
